# Blocklist download request timeout
req_timeout_s: 10

# Also block *.domain.tld
wildcard_block: False

# Cache directory
cache: '.cache/bind_adblock'

# Can be either NULL or NXDOMAIN
blocking_mode: 'NXDOMAIN'

# Blocklists
# List of blocklists
# Format:
#   url: Link to blocklist
#   file: Blocklist file
#   format: domain or hosts, default: domain
lists:
  - file: 'blocklist.txt'
  - url: 'https://pgl.yoyo.org/as/serverlist.php?hostformat=nohtml&showintro=0'
  - url: 'http://winhelp2002.mvps.org/hosts.txt'
    format: hosts
  - url: 'https://adaway.org/hosts.txt'
    format: hosts
  - url: 'https://www.someonewhocares.org/hosts/zero/hosts'
    format: hosts

  # adlists from pi-hole: https://github.com/pi-hole/pi-hole/blob/master/adlists.default
  #
  # The below list amalgamates several lists we used previously.
  # See `https://github.com/StevenBlack/hosts` for details
  # StevenBlack's list
  - url: 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts'
    format: hosts

  # Cameleon
  - url: 'http://sysctl.org/cameleon/hosts'
    format: hosts

  # Disconnect.me Tracking
  - url: 'https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt'

  # Disconnect.me Ads
  - url: 'https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt'

  # Polish CERT - https://www.cert.pl/ostrzezenia_phishing/
  - url: 'https://hole.cert.pl/domains/domains.txt'

# Don't block domains listed here
domain_whitelist: []
